# MySQL. Versions 5.1.10 and up are supported.
#
default: &default

  #RDSデータベース
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: sokuboko
  pool: 5
  username: rio
  password: Orino_1013
  socket: /var/lib/mysql/mysql.sock
  host: illustlife.cczbbshsk7se.ap-northeast-1.rds.amazonaws.com

development:
  <<: *default
  database: sokuboko_test

test:
  <<: *default
  database: sokuboko_test

#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: sokuboko
